### ISSUE TITLE
Generate intiger numbers 0 to10

### ISSUE THREAD

**Issue by AnonymousWebHacker** [TheZlodziej/mqtt-simulator#2]
`<%randi min=0 max=10%>`  no is the command?

**Comment by TheZlodziej** [comment]
I'm not sure what you mean. Yes it is the syntax. 'randi' comes from rand(om)+i(nteger). Although I've had some issues with the arguemnts for certain functions and I recall fixing them. Might have not released them yet - they are on the main branch.

**Comment by AnonymousWebHacker** [comment]
![Captura desde 2024-04-29 22-38-23](https://github.com/TheZlodziej/mqtt-simulator/assets/43164089/41bd066b-5973-4bdb-ad9b-f2c0ee8bf8a6)

**Comment by TheZlodziej** [comment]
Thanks for this issue. I replicated and fixed it locally. Gonna upload it later today once I finish writing tests for the generator to make sure this doesn't happen again

**Comment by TheZlodziej** [comment]
I've published the fix for this

**Comment by AnonymousWebHacker** [comment]
Great :) thnks
