### ISSUE TITLE
Function import json

### ISSUE THREAD

**Issue by AnonymousWebHacker** [TheZlodziej/mqtt-simulator#3]
When you are modifying the topic and its time interval, it would be nice to have a json import instead of writing a whole string

**Comment by TheZlodziej** [comment]
I'll modify file command to accept None as separator so you can print out whole file

**Comment by TheZlodziej** [comment]
Thanks for this issue. You can in fact use file function for that, tho I changed the default separator to None so it reads whole file by default. I need to test it out so I'm gonna upload the changes later today. Current workaround is to put your json in one line and use "\n" separator or one that doesn't appear in json so the split text is going to evaluate to [ your_json ] list.

**Comment by TheZlodziej** [comment]
I will also add a button to import schema from file

**Comment by TheZlodziej** [comment]
@AnonymousWebHacker I've also added the import button during adding/editing topic.

Thanks again for both issues (this & #2). Let me know what you think.

**Comment by AnonymousWebHacker** [comment]
Thank you, it works as expected, it is an excellent function. If you are free, you could implement 2 or 3 more functions, and it would be perfect. Thanks for your code, I am running my project thanks to data generated by your mqtt-simulator :)

**Comment by TheZlodziej** [comment]
Let me know which functions you'd like me to add. I'll try to add those as well.
