### ISSUE TITLE
GPS Simulator Function or others

### ISSUE THREAD

**Issue by AnonymousWebHacker** [TheZlodziej/mqtt-simulator#4]
Could you add a topic that emits a list of GPS data from a simulated route?

1 - When you add a new topic in the 'format' box it could have a checkbox where it says GPS, if you check , in the format text box, an expression is made which would generate simulated GPS values, such as latitude, longitude, height .

Example 1:
![image](https://github.com/TheZlodziej/mqtt-simulator/assets/43164089/4ea6161e-dce4-4e85-97d9-2229a31ccbd3)

Example 2:
![image](https://github.com/TheZlodziej/mqtt-simulator/assets/43164089/008a1995-3dd0-473b-b8d6-da5da384a4f7)

![image](https://github.com/TheZlodziej/mqtt-simulator/assets/43164089/a2fdfeaa-d6ea-4bf3-b695-f37346f18772)

![image](https://github.com/TheZlodziej/mqtt-simulator/assets/43164089/14a19bd4-0295-4b41-a1c5-956333062cfc)

**Comment by TheZlodziej** [comment]
Preformat seems like a nice addition.

**Comment by TheZlodziej** [comment]
I've added patterns that you can load/save on  your own. They are stored in src/patterns directory. I've also redesigned the window you mentioned to make it look more elegant.

<img width="449" alt="image" src="https://github.com/TheZlodziej/mqtt-simulator/assets/33941527/b4880ea4-71c3-4b58-91e2-1655ae242d50">

**Comment by AnonymousWebHacker** [comment]
3 things.
1- I got the same previous theme (maybe because of my gnome-theme)

2- I loved the function of creating my own pattern, very functional

3 - Thanks for everything added, I will be happy to close the issues :)
